trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: mirror-variable-group

steps:
- script: |
    git remote set-url --push origin https://$(github-pat)@github.com/Smarker/mirror-example.git

- task: CmdLine@2
  inputs:
    script: |
      git remote -v
      git fetch -p origin

- task: CmdLine@2
  inputs:
    script: |
      git push --mirror
