# http://blog.plataformatec.com.br/2013/05/how-to-properly-mirror-a-git-repository/

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: mirror-variable-group

steps:
- script: |
    ls
    git clone --mirror https://$(azdo-pat)@dev.azure.com/stmarker/mirror-example/_git/mirror-example
    cd mirror-example.git
    git push --mirror https://$(github-pat)@github.com/Smarker/mirror-example.git
