trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git remote set-url --push origin git@github.com:Smarker/mirror-example.git
    git fetch -p origin
    git push --mirror
  displayName: 'Update github mirror repository'
